In [7]:
import pandas as pd

df = pd.read_csv("../data/raw/obis/occurrences.csv")

df.head()

,basisOfRecord,brackish,catalogNumber,class,classid,collectionCode,country,date_end,date_mid,date_start,...,identifiedBy,eventID,organismID,organismQuantity,organismQuantityType,continent,georeferenceRemarks,recordNumber,recordedBy,stateProvince
0,HumanObservation,True,MCM-LINE-2315524,Teleostei,293496,LINE,South Africa,9.633600e+11,9.633600e+11,9.633600e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HumanObservation,True,NaN,Teleostei,293496,Logbook Program for Coastal Fisheries,NaN,7.928064e+11,7.928064e+11,7.928064e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Occurrence,False,#1306919672015#0.4045515814987244,Teleostei,293496,Patudo (IEO),NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Occurrence,False,#1306919544605#0.8518284173707324,Teleostei,293496,Patudo (IEO),NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HumanObservation,False,MCM-LINE-2097139,Teleostei,293496,LINE,South Africa,9.148896e+11,9.148896e+11,9.148896e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.shape

(100, 92)

In [9]:
df.columns.tolist()

['basisOfRecord',
 'brackish',
 'catalogNumber',
 'class',
 'classid',
 'collectionCode',
 'country',
 'date_end',
 'date_mid',
 'date_start',
 'date_year',
 'day',
 'decimalLatitude',
 'decimalLongitude',
 'eventDate',
 'family',
 'familyid',
 'genus',
 'genusid',
 'gigaclass',
 'gigaclassid',
 'infraphylum',
 'infraphylumid',
 'institutionCode',
 'kingdom',
 'kingdomid',
 'locality',
 'marine',
 'month',
 'order',
 'orderid',
 'parvphylum',
 'parvphylumid',
 'phylum',
 'phylumid',
 'scientificName',
 'scientificNameID',
 'species',
 'speciesid',
 'subfamily',
 'subfamilyid',
 'subphylum',
 'subphylumid',
 'superclass',
 'superclassid',
 'waterBody',
 'year',
 'id',
 'dataset_id',
 'node_id',
 'dropped',
 'absence',
 'originalScientificName',
 'aphiaID',
 'flags',
 'bathymetry',
 'shoredistance',
 'sst',
 'sss',
 'datasetID',
 'depth',
 'individualCount',
 'materialSampleID',
 'maximumDepthInMeters',
 'minimumDepthInMeters',
 'modified',
 'occurrenceID',
 'occurrenceRemarks',
 'occurrenceStatus',
 'scientificNameAuthorship',
 'taxonRank',
 'sex',
 'category',
 'associatedReferences',
 'bibliographicCitation',
 'coordinateUncertaintyInMeters',
 'footprintWKT',
 'specificEpithet',
 'coordinatePrecision',
 'verbatimCoordinates',
 'vernacularName',
 'dynamicProperties',
 'identifiedBy',
 'eventID',
 'organismID',
 'organismQuantity',
 'organismQuantityType',
 'continent',
 'georeferenceRemarks',
 'recordNumber',
 'recordedBy',
 'stateProvince']

In [10]:
df.isnull().sum().sort_values(ascending=False).head(15)

eventID                          99
dynamicProperties                99
organismID                       99
continent                        98
identifiedBy                     98
organismQuantity                 98
organismQuantityType             98
georeferenceRemarks              98
recordedBy                       98
recordNumber                     98
stateProvince                    98
associatedReferences             97
vernacularName                   97
bibliographicCitation            96
coordinateUncertaintyInMeters    95
dtype: int64

In [11]:
useful_columns = [
    "scientificName",
    "species",
    "genus",
    "family",
    "decimalLatitude",
    "decimalLongitude",
    "eventDate",
    "depth",
    "sst",
    "sss",
    "individualCount"
]

df_clean = df[
    [col for col in useful_columns if col in df.columns]
]

df_clean.head()

,scientificName,species,genus,family,decimalLatitude,decimalLongitude,eventDate,depth,sst,sss,individualCount
0,Thunnus albacares,Thunnus albacares,Thunnus,Scombridae,-31.038799,30.232300,2000-07-12T12:00:00Z,NaN,23.58,35.31,NaN
1,Thunnus albacares,Thunnus albacares,Thunnus,Scombridae,27.330000,-89.280000,1995-02-15,162.0,26.11,35.82,3.0
2,Thunnus obesus,Thunnus obesus,Thunnus,Scombridae,18.333473,-20.166805,NaN,NaN,23.26,36.14,NaN
3,Thunnus obesus,Thunnus obesus,Thunnus,Scombridae,0.883472,0.416806,NaN,NaN,27.62,34.70,NaN
4,Thunnus alalunga,Thunnus alalunga,Thunnus,Scombridae,-34.356899,18.497200,1998-12-29T12:00:00Z,NaN,17.19,35.43,NaN

In [12]:
from pathlib import Path

output_dir = Path("../data/processed/obis")
output_dir.mkdir(parents=True, exist_ok=True)

df_clean.to_csv(
    output_dir / "obis_clean.csv",
    index=False
)

print("Processed dataset saved!")

Processed dataset saved!