In [7]:
import pandas as pd

df = pd.read_csv("../data/processed/obis/obis_clean.csv")

df.head()

,scientificName,species,genus,family,decimalLatitude,decimalLongitude,eventDate,depth,sst,sss,individualCount
0,Thunnus albacares,Thunnus albacares,Thunnus,Scombridae,-31.038799,30.232300,2000-07-12T12:00:00Z,NaN,23.58,35.31,NaN
1,Thunnus albacares,Thunnus albacares,Thunnus,Scombridae,27.330000,-89.280000,1995-02-15,162.0,26.11,35.82,3.0
2,Thunnus obesus,Thunnus obesus,Thunnus,Scombridae,18.333473,-20.166805,NaN,NaN,23.26,36.14,NaN
3,Thunnus obesus,Thunnus obesus,Thunnus,Scombridae,0.883472,0.416806,NaN,NaN,27.62,34.70,NaN
4,Thunnus alalunga,Thunnus alalunga,Thunnus,Scombridae,-34.356899,18.497200,1998-12-29T12:00:00Z,NaN,17.19,35.43,NaN

In [8]:
df[["decimalLatitude", "decimalLongitude"]].head()

   decimalLatitude  decimalLongitude
0       -31.038799         30.232300
1        27.330000        -89.280000
2        18.333473        -20.166805
3         0.883472          0.416806
4       -34.356899         18.497200

In [9]:
map_df = df.dropna(
    subset=["decimalLatitude", "decimalLongitude"]
).copy()

print(f"Records available for mapping: {len(map_df)}")

Records available for mapping: 100

In [10]:
import folium

m = folium.Map(
    location=[20, 0],
    zoom_start=2
)

for _, row in map_df.iterrows():

    folium.CircleMarker(
        location=[
            row["decimalLatitude"],
            row["decimalLongitude"]
        ],
        radius=5,
        popup=row.get("scientificName", "Unknown species"),
        fill=True
    ).add_to(m)

m

In [11]:
m.save("../data/processed/obis/obis_species_map.html")

print("Map saved!")

Map saved!

In [12]:
import pandas as pd
import folium
from folium.plugins import MarkerCluster

df = pd.read_csv("../data/processed/obis/obis_clean.csv")

map_df = df.dropna(
    subset=["decimalLatitude", "decimalLongitude"]
).copy()

print(f"Records available: {len(map_df)}")

Records available: 100

In [ ]:
m = folium.Map(
    location=[20, 0],
    zoom_start=2
)

marker_cluster = MarkerCluster().add_to(m)

for _, row in map_df.iterrows():

    species = row.get("scientificName", "Unknown")
    latitude = row["decimalLatitude"]
    longitude = row["decimalLongitude"]

    depth = row.get("depth", "N/A")
    sst = row.get("sst", "N/A")
    sss = row.get("sss", "N/A")
    date = row.get("eventDate", "N/A")

    popup = f"""
    <b>Species:</b> {species}<br>
    <b>Latitude:</b> {latitude}<br>
    <b>Longitude:</b> {longitude}<br>
    <b>Depth:</b> {depth}<br>
    <b>Sea Surface Temperature:</b> {sst}<br>
    <b>Sea Surface Salinity:</b> {sss}<br>
    <b>Date:</b> {date}
    """

    folium.CircleMarker(
        location=[latitude, longitude],
        radius=5,
        popup=folium.Popup(popup, max_width=350),
        fill=True
    ).add_to(marker_cluster)

m